# Generated by Django 5.1.7 on 2025-07-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
